project: renewable-energy-templatee
storage:
  - name: data
    type: s3
scripts:
  - name: renewable-energy
    run_on_start: true
    # Must match Dockerfile WORKDIR so SPAI mounts spai.vars.json here
    workdir: /app2
    image: europe-west1-docker.pkg.dev/spai-430907/spai-build/renewable-energy-template-script:latest
apis:
  - name: api
    port: 8021
    host: localhost
    workdir: /app
    image: europe-west1-docker.pkg.dev/spai-430907/spai-build/renewable-energy-template-api:latest
    autoscaling:
      min: 1
      max: 1
      keep_alive: 60
uis:
  - name: map
    # command: npm run dev # for local development
    command: npm run deploy
    port: 5173
    runtime: node
    workdir: /app
    image: europe-west1-docker.pkg.dev/spai-430907/spai-build/renewable-energy-template-ui:latest
    autoscaling:
      min: 1
      max: 1
      keep_alive: 60
    env:
      API_URL: api.api
