project: renewable-energy-template
storage:
  - name: data
    type: s3
scripts:
  - name: renewable-energy
    run_on_start: true
apis:
  - name: api
    port: 8021
    host: localhost
uis:
  - name: map
    # command: npm run dev # for local development
    command: npm run deploy
    port: 5173
    runtime: node
    env:
      API_URL: api.api
