project: renewable-energy
storage:
  - name: data
    type: s3
scripts:
  - name: renewable-energy
    run_on_start: true
apis:
  - name: analytics
    port: 8021
    host: localhost
  - name: xyz
    port: 8022
    host: localhost
uis:
  - name: map
    # command: npm run dev # for local development
    command: npm run deploy
    port: 5173
    runtime: node
    env:
      ANALYTICS_URL: api.analytics
      XYZ_URL: api.xyz
