FROM ghcr.io/astral-sh/uv:0.6.17-python3.12-bookworm-slim

WORKDIR /app2

RUN uv venv

COPY requirements.txt .

RUN uv pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uv", "run", "main.py"]